#!/usr/bin/env python
import sys
from flake8.main import git

if __name__ == '__main__':
    sys.exit(git.hook(
        # return non-zero depending on warnings found.  This will cause the commit to abort.
        strict=True,
        # Detects files not in the index to indicate warnings if using `git commit -a`.
        lazy=True,
    ))
